[package]
name = "bao_bin"
version = "0.2.0"
authors = ["Jack O'Connor"]

[[bin]]
name = "bao"
path = "src/main.rs"

[dependencies]
arrayref = "0.3.4"
bao = { path = ".." }
docopt = "1.0.1"
failure = "0.1.2"
hex = "0.3.2"
memmap = "0.6.2"
os_pipe = "0.7.0"
serde = "1.0.75"
serde_derive = "1.0.75"

[dev-dependencies]
duct = "0.11.0"
rand = "0.5.5"
tempfile = "3.0.3"
