language: rust
os:
  - linux
  - osx
  - windows
rust:
  - stable
  - beta
  - nightly
script:
  # With std (and any other optional features that might be added in the future).
  - cargo test -vv --all-features
  # Without std. Currently only the build is supported.
  - cargo build -vv --no-default-features
  # Test the bao_bin sub-crate.
  - (cd bao_bin && cargo test -vv)
