language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
script:
  # With std, but skip python tests.
  - cargo test -vv --no-default-features --features std
  # Without std. Currently only the build is supported.
  - cargo build -vv --no-default-features
