environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    VERSION: 1.28.0
  - TARGET: i686-pc-windows-msvc
    VERSION: 1.28.0
  - TARGET: i686-pc-windows-gnu
    VERSION: 1.28.0
  - TARGET: x86_64-pc-windows-msvc
    VERSION: beta
  - TARGET: i686-pc-windows-msvc
    VERSION: beta
  - TARGET: i686-pc-windows-gnu
    VERSION: beta
  - TARGET: x86_64-pc-windows-msvc
    VERSION: nightly
  - TARGET: i686-pc-windows-msvc
    VERSION: nightly
  - TARGET: i686-pc-windows-gnu
    VERSION: nightly
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:VERSION}-${env:TARGET}.exe"
  - rust-%VERSION%-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  # With std (and any other optional features that might be added in the future).
  - cargo test -vv --all-features
  # Without std. Currently only the build is supported.
  - cargo build -vv --no-default-features
  # Test the bao_bin sub-crate.
  - cd bao_bin
  - cargo test -vv
