[package]
authors = ["jacko"]
name = "bao"
version = "0.2.0"
description = "a general purpose tree hash for files"
license = "MIT"
repository = "https://github.com/oconnor663/bao"

[features]
default = ["std"]
std = ["byteorder/std", "blake2b_simd/std", "rayon"]

[dependencies]
arrayref = "0.3.4"
arrayvec = { version = "0.4.7", default-features = false, features = ["use_union"] }
byteorder = { version = "1.2.4", default-features = false }
blake2b_simd = { version = "0.2.3", default-features = false }
constant_time_eq = "0.1.3"
copy_in_place = "0.1.0"
rayon = { version = "1.0.2", optional = true }

[dev-dependencies]
duct = "0.11.0"
hex = "0.3.2"
rand = "0.5.5"
tempfile = "3.0.3"
