[package]
authors = ["jacko"]
name = "bao"
version = "0.1.0"
description = "a general purpose tree hash for files"
license = "MIT"
repository = "https://github.com/oconnor663/bao"

[dependencies]
arrayref = "0.3.4"
arrayvec = "0.4.6"
byteorder = "1.1.0"
blake2_c = "0.3.0"
docopt = "0.8.1"
hex = "0.2.0"
ring = "0.13.0-alpha"
serde = "1.0.20"
serde_derive = "1.0.20"

[dev-dependencies]
rand = "0.3.17"
duct = "0.9.2"

[features]
native = ["blake2_c/native"]
