[package]
name = "bao"
version = "0.9.0"
authors = ["Jack O'Connor"]
description = "a general-purpose cryptographic tree hash"
license = "MIT"
repository = "https://github.com/oconnor663/bao"
documentation = "https://docs.rs/bao"
readme = "README.md"
edition = "2018"

[features]
default = ["std"]
std = ["blake2s_simd/std", "num_cpus", "rayon"]

[dependencies]
arrayref = "0.3.5"
arrayvec = { version = "0.4.11", default-features = false, features = ["array-sizes-33-128"] }
blake2s_simd = { version = "0.5.6", default-features = false }
constant_time_eq = "0.1.3"
num_cpus = { version = "1.10.1", optional = true }
rayon = { version = "1.1.0", optional = true }

[dev-dependencies]
lazy_static = "1.3.0"
rand = "0.7.0"
serde = { version = "1.0.97", features = ["derive"] }
serde_json = "1.0.40"
tempfile = "3.1.0"
rand_chacha = "0.2.0"
rand_xorshift = "0.2.0"
page_size = "0.4.1"
