[package]
authors = ["jacko"]
name = "bao"
version = "0.1.0"
description = "a general purpose tree hash for files"
license = "MIT"
repository = "https://github.com/oconnor663/bao"

[dependencies]
arrayref = "0.3.4"
byteorder = "1.1.0"
blake2_c = "0.1.0"
clap = "2.26.2"
hex = "0.2.0"
ring = "0.12.1"

[dev-dependencies]
rand = "0.3.17"
duct = "0.9.2"
