[package]
authors = ["jacko"]
name = "bao"
version = "0.1.0"
description = "a general purpose tree hash for files"
license = "MIT"
repository = "https://github.com/oconnor663/bao"

[dependencies]
arrayref = "0.3.4"
arrayvec = "0.4.7"
byteorder = "1.2.1"
blake2_c = "0.3.0"
constant_time_eq = "0.1.3"
crossbeam = "0.3.2"
docopt = "0.8.3"
either = "1.5.0"
hex = "0.3.1"
lazy_static = "1.0.0"
libc = "0.2.42"
memmap = "0.6.2"
num_cpus = "1.8.0"
rayon = "1.0.0"
serde = "1.0.27"
serde_derive = "1.0.27"

[dev-dependencies]
rand = "0.4.2"
duct = "0.10.0"

[features]
native = ["blake2_c/native"]
